module.exports = {
  // For complete listing of rules and what they do, check out the docs.
  // See: https://github.com/evcohen/eslint-plugin-jsx-a11y
  rules: {
    'metalab/jsx-a11y/accessible-emoji': 'error',
    'metalab/jsx-a11y/alt-text': 'error',
    'metalab/jsx-a11y/anchor-has-content': 0,
    'metalab/jsx-a11y/anchor-is-valid': 'error',
    'metalab/jsx-a11y/aria-activedescendant-has-tabindex': 'error',
    'metalab/jsx-a11y/aria-props': 'error',
    'metalab/jsx-a11y/aria-proptypes': 'error',
    'metalab/jsx-a11y/aria-role': 'error',
    'metalab/jsx-a11y/aria-unsupported-elements': 'error',
    'metalab/jsx-a11y/click-events-have-key-events': 'error',
    'metalab/jsx-a11y/heading-has-content': 'error',
    'metalab/jsx-a11y/html-has-lang': 'error',
    'metalab/jsx-a11y/iframe-has-title': 'error',
    'metalab/jsx-a11y/img-redundant-alt': 'error',
    'metalab/jsx-a11y/interactive-supports-focus': [
      'error',
      {
        tabbable: [
          'button',
          'checkbox',
          'link',
          'progressbar',
          'searchbox',
          'slider',
          'spinbutton',
          'switch',
          'textbox',
        ],
      },
    ],
    'metalab/jsx-a11y/label-has-for': 0,
    'metalab/jsx-a11y/media-has-caption': 0,
    'metalab/jsx-a11y/mouse-events-have-key-events': 'error',
    'metalab/jsx-a11y/no-access-key': 'error',
    'metalab/jsx-a11y/no-autofocus': 'error',
    'metalab/jsx-a11y/no-distracting-elements': 'error',
    'metalab/jsx-a11y/no-interactive-element-to-noninteractive-role': 'error',
    'metalab/jsx-a11y/no-noninteractive-element-interactions': 0,
    'metalab/jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
    'metalab/jsx-a11y/no-noninteractive-tabindex': 'error',
    'metalab/jsx-a11y/no-onchange': 0,
    'metalab/jsx-a11y/no-redundant-roles': 'error',
    'metalab/jsx-a11y/no-static-element-interactions': 'error',
    'metalab/jsx-a11y/role-has-required-aria-props': 'error',
    'metalab/jsx-a11y/role-supports-aria-props': 'error',
    'metalab/jsx-a11y/scope': 'error',
    'metalab/jsx-a11y/tabindex-no-positive': 'error',
  },
};
